using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Emit;
using Weft.Compiler.Backends;
using Weft.Compiler.Diagnostics;
using Weft.Compiler.IR;
using Weft.Compiler.Semantics;
using Weft.Compiler.Text;
using Weft.Runtime;
using Diagnostic = Weft.Compiler.Diagnostics.Diagnostic;
using DiagnosticSeverity = Weft.Compiler.Diagnostics.DiagnosticSeverity;
using TypeKind = Weft.Compiler.Semantics.TypeKind;

namespace Weft.Backend.DotNet;

public sealed class DotNetEmitter
{
    public GeneratedSource Generate(IrModule module, FunctionSymbol entry)
    {
        var writer = new SourceWriter();
        writer.WriteLine("// Generated by Weft. Edit the .weft source.");
        writer.WriteLine("internal static class WeftProgram {");
        writer.WriteLine("public static int Main(string[] args) {");
        writer.WriteLine($"Weft.Runtime.RuntimeContract.RequireAbi({Quote(module.RuntimeAbi)});");
        writer.WriteLine(entry.ReturnType == WeftType.Void ? $"f_{entry.Id}(); return 0;" : $"return f_{entry.Id}();");
        writer.WriteLine("}");
        foreach (var type in module.Classes.IsDefault ? [] : module.Classes)
        {
            writer.WriteLine($"private sealed class {ObjectEmission.TypeName(new(TypeKind.Nominal, type.Symbol.Name))} {{", new(type.Symbol.Location));
            foreach (var field in type.Fields) writer.WriteLine($"public {(field.IsStatic ? "static " : "")}{Type(field.Type)} m_{field.Id};", new(field.Location));
            var name = ObjectEmission.TypeName(new(TypeKind.Nominal, type.Symbol.Name));
            if (type.TypeInitializer is { } initializer)
                writer.WriteLine($"static {name}() {{ f_{initializer.Id}(); }}");
            writer.WriteLine("public static void touch() { }");
            if (type.Symbol.Kind is DataKind.Record or DataKind.Model)
            {
                writer.WriteLine($"public {name} weftCopy() {{");
                if (type.CopyConstructor is { } copyConstructor) writer.WriteLine($"return f_{copyConstructor.Id}(this); }}");
                else
                {
                    writer.WriteLine($"{name} copy = new {name}();");
                    foreach (var field in type.Fields.Where(f => !f.IsStatic)) writer.WriteLine($"copy.m_{field.Id} = this.m_{field.Id};");
                    writer.WriteLine("return copy; }");
                }
            }
            if (type.Symbol.Kind == DataKind.Record)
            {
                writer.WriteLine("public override bool Equals(object obj) {");
                writer.WriteLine($"return System.Object.ReferenceEquals(this, obj) || obj is {name} other" + string.Concat(type.Fields.Where(f => !f.IsStatic).Select(f => $" && System.Collections.Generic.EqualityComparer<{Type(f.Type)}>.Default.Equals(m_{f.Id}, other.m_{f.Id})")) + "; }");
                writer.WriteLine("public override int GetHashCode() { var hash = new System.HashCode();");
                foreach (var field in type.Fields.Where(f => !f.IsStatic)) writer.WriteLine($"hash.Add(m_{field.Id});");
                writer.WriteLine("return hash.ToHashCode(); }");
            }
            writer.WriteLine("}");
        }
        foreach (var (ignored, result) in ObjectEmission.Sequences(module))
            writer.WriteLine($"private static {Type(result)} {ObjectEmission.SequenceName(ignored, result)}({Type(ignored)} ignored, {Type(result)} result) {{ return result; }}");
        foreach (var setter in ObjectEmission.Setters(module))
        {
            var receiverParameter = setter.Receiver is null ? "" : $"{Type(setter.Receiver.Type)} receiver, ";
            writer.WriteLine($"private static {Type(setter.Parameters[0].Type)} p_{setter.Id}({receiverParameter}{Type(setter.Parameters[0].Type)} value) {{", new(setter.Location, "property-assignment"));
            writer.WriteLine($"f_{setter.Id}({(setter.Receiver is null ? "" : "receiver, ")}value); return value;");
            writer.WriteLine("}");
        }
        foreach (var function in module.Functions)
        {
            writer.WriteLine($"#line {function.Origin.Location.Line} {Quote(function.Origin.Location.File)}");
            writer.WriteLine($"private static {Type(function.Symbol.ReturnType)} f_{function.Symbol.Id}({string.Join(", ", ObjectEmission.Parameters(function.Symbol).Select(p => $"{Type(p.Type)} v_{p.Id}"))})", function.Origin);
            writer.WriteLine("{");
            if (function.Symbol.ContainingType is { } owner && !function.Symbol.IsTypeInitializer)
                writer.WriteLine($"{ObjectEmission.TypeName(new(TypeKind.Nominal, owner))}.touch();");
            foreach (var temporary in ObjectEmission.Temporaries(function)) writer.WriteLine($"{Type(temporary.Type)} v_{temporary.Id};");
            Statement(function.Body); writer.WriteLine("}");
        }
        foreach (var call in CallAdapters.Collect(module))
        {
            var parameters = string.Join(", ", call.Arguments.Select((argument, i) => $"{Type(argument.Type)} a_{i}"));
            if (call.Receiver is not null) parameters = $"{Type(call.Receiver.Type)} receiver" + (parameters.Length > 0 ? ", " + parameters : "");
            var arguments = string.Join(", ", Enumerable.Range(0, call.Arguments.Length).Select(i => $"a_{call.ParameterOrder.IndexOf(i)}"));
            if (call.Receiver is not null) arguments = "receiver" + (arguments.Length > 0 ? ", " + arguments : "");
            writer.WriteLine($"private static {Type(call.Type)} {CallAdapters.Name(call)}({parameters}) => f_{call.Function.Id}({arguments});",
                new(call.Origin.Location, "named-argument-adapter", call.Origin));
        }
        writer.WriteLine("#line default");
        writer.WriteLine("}");
        return writer.Finish("WeftProgram.cs");

        void Statement(IrStatement statement)
        {
            writer.WriteLine($"#line {statement.Origin.Location.Line} {Quote(statement.Origin.Location.File)}");
            switch (statement)
            {
                case IrBlock block:
                    writer.WriteLine("{", block.Origin);
                    foreach (var child in block.Statements) Statement(child);
                    writer.WriteLine("}"); break;
                case IrVariable variable: writer.WriteLine($"{Type(variable.Symbol.Type)} v_{variable.Symbol.Id} = {Expression(variable.Initializer)};", variable.Origin); break;
                case IrReturn returned: writer.WriteLine(returned.Expression is null ? "return;" : $"return {Expression(returned.Expression)};", returned.Origin); break;
                case IrExpressionStatement expression: writer.WriteLine($"{StatementExpression(expression.Expression)};", expression.Origin); break;
                case IrIf conditional:
                    writer.WriteLine($"if ({Expression(conditional.Condition)})", conditional.Origin);
                    writer.WriteLine("{"); Statement(conditional.Then); writer.WriteLine("}");
                    if (conditional.Else is not null) { writer.WriteLine("else {"); Statement(conditional.Else); writer.WriteLine("}"); }
                    break;
                case IrWhile loop:
                    writer.WriteLine($"while ({Expression(loop.Condition)})", loop.Origin);
                    writer.WriteLine("{"); Statement(loop.Body); writer.WriteLine("}"); break;
                case IrBreak: writer.WriteLine("break;", statement.Origin); break;
                case IrContinue: writer.WriteLine("continue;", statement.Origin); break;
                case IrDoWhile loop:
                    writer.WriteLine("do {", loop.Origin); Statement(loop.Body);
                    writer.WriteLine($"}} while ({Expression(loop.Condition)});", loop.Origin); break;
                case IrFor loop:
                    // A surrounding block gives initializer locals their exact Weft
                    // scope. A native for preserves continue -> iterators -> condition.
                    writer.WriteLine("{", loop.Origin);
                    foreach (var initializer in loop.Initializers) Statement(initializer);
                    var condition = loop.Condition is null ? "true" : Expression(loop.Condition);
                    var iterators = ControlFlow.ReachesIterator(loop.Body)
                        ? string.Join(", ", loop.Iterators.Select(StatementExpression)) : "";
                    writer.WriteLine($"for (; {condition}; {iterators}) {{", loop.Origin);
                    Statement(loop.Body); writer.WriteLine("}"); writer.WriteLine("}"); break;
                default: throw new InvalidOperationException($"Unsupported IR statement {statement.GetType().Name}.");
            }
        }
    }

    private static string Type(WeftType type) => type.Kind switch
    {
        TypeKind.Void => "void", TypeKind.Bool => "bool", TypeKind.Int32 => "int", TypeKind.Int64 => "long", TypeKind.String => "string",
        TypeKind.Nominal => ObjectEmission.TypeName(type),
        _ => throw new InvalidOperationException($"Unsupported IR type '{type.Name}'.")
    };
    internal static string Quote(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
    private static string Update(IrUpdate update) => update.Postfix
        ? $"v_{update.Symbol.Id}{update.Operator}" : $"{update.Operator}v_{update.Symbol.Id}";
    private static string StatementExpression(IrExpression expression) => expression switch
    {
        IrAssign assign => $"v_{assign.Symbol.Id} = {Expression(assign.Value)}",
        IrFieldWrite write => $"{FieldTarget(write.Field, write.Receiver)} = {Expression(write.Value)}",
        IrFieldUpdate update => FieldUpdate(update),
        IrUpdate update => Update(update),
        _ => Expression(expression)
    };
    private static string FieldTarget(FieldSymbol field, IrExpression? receiver) =>
        field.IsStatic ? $"{ObjectEmission.TypeName(field.Owner)}.m_{field.Id}" : $"({Expression(receiver!)}).m_{field.Id}";
    private static string ReadField(IrFieldRead read)
    {
        var field = FieldTarget(read.Field, read.Receiver);
        return read.Field.IsStatic && read.Type.Kind is TypeKind.String or TypeKind.Nominal
            ? $"Weft.Runtime.RuntimeContract.ReadStatic({field}, {Quote(read.Field.Owner.Name + "." + read.Field.Name)})" : field;
    }
    private static string FieldUpdate(IrFieldUpdate update) => update.Postfix
        ? $"{FieldTarget(update.Field, update.Receiver)}{update.Operator}"
        : $"{update.Operator}{FieldTarget(update.Field, update.Receiver)}";
    private static string Expression(IrExpression expression) => expression switch
    {
        IrConstant constant => constant.Value switch
        {
            string value => Quote(value), bool value => value ? "true" : "false",
            int value => value.ToString(CultureInfo.InvariantCulture), long value => value.ToString(CultureInfo.InvariantCulture) + "L",
            _ => throw new InvalidOperationException("Unsupported IR constant.")
        },
        IrConditional conditional => $"({Expression(conditional.Condition)} ? {Expression(conditional.WhenTrue)} : {Expression(conditional.WhenFalse)})",
        IrUpdate update => $"unchecked({Update(update)})",
        IrSetterCall setter => $"p_{setter.Setter.Id}({(setter.Receiver is null ? "" : Expression(setter.Receiver) + ", ")}{Expression(setter.Value)})",
        IrCopy copy => $"({Expression(copy.Receiver)}).weftCopy()",
        IrObjectHash hash => $"({Expression(hash.Receiver)}).GetHashCode()",
        IrAllocate allocated => $"new {Type(allocated.Type)}()",
        IrFieldRead read => ReadField(read),
        IrFieldWrite write => $"({FieldTarget(write.Field, write.Receiver)} = {Expression(write.Value)})",
        IrFieldUpdate update => $"unchecked({FieldUpdate(update)})",
        IrSequence sequence => ObjectEmission.Sequence(sequence, Expression),
        IrRead read => $"v_{read.Symbol.Id}",
        IrConvert convert => $"((long)({Expression(convert.Operand)}))",
        IrAssign assign => $"(v_{assign.Symbol.Id} = {Expression(assign.Value)})",
        IrUnary unary => $"unchecked({unary.Operator}({Expression(unary.Operand)}))",
        IrBinary binary when binary.Left.Type.Kind == TypeKind.Nominal && binary.Operator is "==" or "!=" => $"({(binary.Operator == "!=" ? "!" : "")}System.Object.Equals({Expression(binary.Left)}, {Expression(binary.Right)}))",
        IrBinary binary when binary.Operator is "/" or "%" => $"Weft.Runtime.RuntimeContract.{(binary.Operator == "/" ? "Divide" : "Remainder")}({Expression(binary.Left)}, {Expression(binary.Right)})",
        IrBinary binary => $"unchecked({Expression(binary.Left)} {binary.Operator} {Expression(binary.Right)})",
        IrCall call => $"{CallAdapters.Name(call)}({string.Join(", ", ObjectEmission.Arguments(call).Select(Expression))})",
        IrIntrinsic intrinsic => $"Weft.Runtime.RuntimeContract.{(intrinsic.Signature.Name == Intrinsics.Print.Name ? "WriteLine" : "Text")}({string.Join(", ", intrinsic.Arguments.Select(Expression))})",
        _ => throw new InvalidOperationException($"Unsupported IR expression {expression.GetType().Name}.")
    };

    public async Task<BackendResult> BuildAsync(IrModule module, string entryName, string outputDirectory, RuntimeDescriptor? runtime = null, CancellationToken cancellation = default)
    {
        var diagnostics = new DiagnosticBag();
        diagnostics.AddRange(IrValidator.Validate(module));
        diagnostics.AddRange((runtime ?? RuntimeDescriptor.Bootstrap).Validate(module));
        var entry = EntryPoint.Resolve(module, entryName, diagnostics);
        if (diagnostics.HasErrors || entry is null) return new(null, new("WeftProgram.cs", "", []), diagnostics.ToImmutableArray());
        return await CompileGeneratedAsync(Generate(module, entry), module.Name, outputDirectory, cancellation);
    }

    public async Task<BackendResult> CompileGeneratedAsync(GeneratedSource source, string name, string outputDirectory, CancellationToken cancellation = default)
    {
        Directory.CreateDirectory(outputDirectory);
        var sourcePath = Path.Combine(outputDirectory, source.FileName);
        await File.WriteAllTextAsync(sourcePath, source.Text, new UTF8Encoding(false), cancellation);
        await File.WriteAllTextAsync(sourcePath + ".map.json", JsonSerializer.Serialize(source.Lines), cancellation);
        var tree = CSharpSyntaxTree.ParseText(Microsoft.CodeAnalysis.Text.SourceText.From(source.Text, Encoding.UTF8), new CSharpParseOptions(LanguageVersion.CSharp14), sourcePath, cancellationToken: cancellation);
        var references = ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ?? "").Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Append(typeof(RuntimeContract).Assembly.Location).Distinct(StringComparer.Ordinal).Select(path => MetadataReference.CreateFromFile(path));
        var compilation = CSharpCompilation.Create(name, [tree], references,
            new CSharpCompilationOptions(OutputKind.ConsoleApplication, optimizationLevel: OptimizationLevel.Release, checkOverflow: false, deterministic: true));
        var artifact = Path.Combine(outputDirectory, name + ".dll");
        using var pe = new MemoryStream();
        using var pdb = new MemoryStream();
        var emitted = compilation.Emit(pe, pdb, options: new EmitOptions(debugInformationFormat: DebugInformationFormat.PortablePdb), cancellationToken: cancellation);
        var diagnostics = emitted.Diagnostics.Where(d => d.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error).Select(d =>
        {
            var line = d.Location.GetLineSpan().StartLinePosition.Line + 1;
            return new Diagnostic("WF4101", $"C# {d.Id}: {d.GetMessage(CultureInfo.InvariantCulture)}", source.Location(line), DiagnosticSeverity.Error);
        }).ToImmutableArray();
        if (!emitted.Success) return new(null, source, diagnostics);
        await File.WriteAllBytesAsync(artifact, pe.ToArray(), cancellation);
        await File.WriteAllBytesAsync(Path.Combine(outputDirectory, name + ".pdb"), pdb.ToArray(), cancellation);
        File.Copy(typeof(RuntimeContract).Assembly.Location, Path.Combine(outputDirectory, "Weft.Runtime.dll"), overwrite: true);
        var config = new { runtimeOptions = new { tfm = "net10.0", framework = new { name = "Microsoft.NETCore.App", version = "10.0.0" } } };
        await File.WriteAllTextAsync(Path.Combine(outputDirectory, name + ".runtimeconfig.json"), JsonSerializer.Serialize(config), cancellation);
        return new(artifact, source, diagnostics);
    }
}
