using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Weft.Compiler.Backends;
using Weft.Compiler.Diagnostics;
using Weft.Compiler.IR;
using Weft.Compiler.Semantics;

namespace Weft.Backend.Jvm;

public sealed partial class JvmEmitter
{
    public GeneratedSource Generate(IrModule module, FunctionSymbol entry)
    {
        var writer = new SourceWriter();
        writer.WriteLine("// Generated by Weft. Edit the .weft source.");
        writer.WriteLine("public final class WeftProgram {");
        writer.WriteLine("public static void main(String[] args) {");
        writer.WriteLine($"weft.runtime.RuntimeContract.requireAbi({Quote(module.RuntimeAbi)});");
        writer.WriteLine(entry.ReturnType == WeftType.Void ? $"f_{entry.Id}();" : $"System.exit(f_{entry.Id}());");
        writer.WriteLine("}");
        foreach (var function in module.Functions)
        {
            writer.WriteLine($"private static {Type(function.Symbol.ReturnType)} f_{function.Symbol.Id}({string.Join(", ", function.Symbol.Parameters.Select(p => $"{Type(p.Type)} v_{p.Id}"))})", function.Origin);
            Statement(function.Body);
        }
        foreach (var call in CallAdapters.Collect(module))
        {
            var parameters = string.Join(", ", call.Arguments.Select((argument, i) => $"{Type(argument.Type)} a_{i}"));
            var arguments = string.Join(", ", Enumerable.Range(0, call.Arguments.Length).Select(i => $"a_{call.ParameterOrder.IndexOf(i)}"));
            writer.WriteLine($"private static {Type(call.Type)} {CallAdapters.Name(call)}({parameters}) {{ {(call.Type == WeftType.Void ? "" : "return ")}f_{call.Function.Id}({arguments}); }}",
                new(call.Origin.Location, "named-argument-adapter", call.Origin));
        }
        writer.WriteLine("}");
        return writer.Finish("WeftProgram.java");

        void Statement(IrStatement statement)
        {
            switch (statement)
            {
                case IrBlock block:
                    writer.WriteLine("{", block.Origin);
                    foreach (var child in block.Statements) Statement(child);
                    writer.WriteLine("}"); break;
                case IrVariable variable: writer.WriteLine($"{Type(variable.Symbol.Type)} v_{variable.Symbol.Id} = {Expression(variable.Initializer)};", variable.Origin); break;
                case IrReturn returned: writer.WriteLine(returned.Expression is null ? "return;" : $"return {Expression(returned.Expression)};", returned.Origin); break;
                case IrExpressionStatement expression: writer.WriteLine($"{StatementExpression(expression.Expression)};", expression.Origin); break;
                case IrIf conditional:
                    writer.WriteLine($"if ({Expression(conditional.Condition)})", conditional.Origin);
                    writer.WriteLine("{"); Statement(conditional.Then); writer.WriteLine("}");
                    if (conditional.Else is not null) { writer.WriteLine("else {"); Statement(conditional.Else); writer.WriteLine("}"); }
                    break;
                case IrWhile loop:
                    // Avoid javac's special constant-condition reachability rules.
                    writer.WriteLine($"while (Boolean.valueOf({Expression(loop.Condition)}).booleanValue())", loop.Origin);
                    writer.WriteLine("{"); Statement(loop.Body); writer.WriteLine("}"); break;
                default: throw new InvalidOperationException($"Unsupported IR statement {statement.GetType().Name}.");
            }
        }
    }
    private static string Type(WeftType type) => type.Kind switch
    {
        TypeKind.Void => "void", TypeKind.Bool => "boolean", TypeKind.Int32 => "int", TypeKind.Int64 => "long", TypeKind.String => "String",
        _ => throw new InvalidOperationException($"Unsupported IR type '{type.Name}'.")
    };
    private static string Quote(string value)
    {
        var text = new StringBuilder("\"");
        foreach (char ch in value)
            text.Append(ch switch { '\\' => "\\\\", '"' => "\\\"", '\n' => "\\n", '\r' => "\\r", '\t' => "\\t", '\0' => "\\000", _ when ch < 32 || ch > 126 => "\\u" + ((int)ch).ToString("x4", CultureInfo.InvariantCulture), _ => ch.ToString() });
        return text.Append('"').ToString();
    }
    private static string StatementExpression(IrExpression expression) => expression is IrAssign assign ? $"v_{assign.Symbol.Id} = {Expression(assign.Value)}" : Expression(expression);
    private static string Expression(IrExpression expression) => expression switch
    {
        IrConstant constant => constant.Value switch
        {
            string value => Quote(value), bool value => value ? "true" : "false",
            int value => value.ToString(CultureInfo.InvariantCulture), long value => value.ToString(CultureInfo.InvariantCulture) + "L",
            _ => throw new InvalidOperationException("Unsupported IR constant.")
        },
        IrRead read => $"v_{read.Symbol.Id}",
        IrConvert convert => $"((long)({Expression(convert.Operand)}))",
        IrAssign assign => $"(v_{assign.Symbol.Id} = {Expression(assign.Value)})",
        IrUnary unary => $"({unary.Operator}({Expression(unary.Operand)}))",
        IrBinary binary when binary.Left.Type == WeftType.String && binary.Operator is "==" or "!=" => $"({(binary.Operator == "!=" ? "!" : "")}({Expression(binary.Left)}).equals({Expression(binary.Right)}))",
        IrBinary binary when binary.Operator is "/" or "%" => $"weft.runtime.RuntimeContract.{(binary.Operator == "/" ? "divide" : "remainder")}({Expression(binary.Left)}, {Expression(binary.Right)})",
        IrBinary binary => $"({Expression(binary.Left)} {binary.Operator} {Expression(binary.Right)})",
        IrCall call => $"{CallAdapters.Name(call)}({string.Join(", ", call.Arguments.Select(Expression))})",
        IrIntrinsic intrinsic => $"weft.runtime.RuntimeContract.{(intrinsic.Signature.Name == Intrinsics.Print.Name ? "writeLine" : "text")}({string.Join(", ", intrinsic.Arguments.Select(Expression))})",
        _ => throw new InvalidOperationException($"Unsupported IR expression {expression.GetType().Name}.")
    };
    public async Task<BackendResult> BuildAsync(IrModule module, string entryName, string outputDirectory, RuntimeDescriptor? runtime = null, CancellationToken cancellation = default)
    {
        var diagnostics = new DiagnosticBag();
        diagnostics.AddRange(IrValidator.Validate(module));
        diagnostics.AddRange((runtime ?? RuntimeDescriptor.Bootstrap).Validate(module));
        var entry = EntryPoint.Resolve(module, entryName, diagnostics);
        if (diagnostics.HasErrors || entry is null) return new(null, new("WeftProgram.java", "", []), diagnostics.ToImmutableArray());
        return await CompileGeneratedAsync(Generate(module, entry), module.Name, outputDirectory, cancellation);
    }

    public async Task<BackendResult> CompileGeneratedAsync(GeneratedSource source, string name, string outputDirectory, CancellationToken cancellation = default)
    {
        outputDirectory = Path.GetFullPath(outputDirectory);
        Directory.CreateDirectory(outputDirectory);
        var sourcePath = Path.Combine(outputDirectory, source.FileName);
        await File.WriteAllTextAsync(sourcePath, source.Text, new UTF8Encoding(false), cancellation);
        await File.WriteAllTextAsync(sourcePath + ".map.json", JsonSerializer.Serialize(source.Lines), cancellation);
        var classes = Path.Combine(outputDirectory, "classes");
        Directory.CreateDirectory(classes);
        var runtime = Path.Combine(AppContext.BaseDirectory, "runtime", "jvm");
        var runtimeSources = Directory.Exists(runtime) ? Directory.GetFiles(runtime, "*.java", SearchOption.AllDirectories).Order(StringComparer.Ordinal).ToArray() : [];
        if (runtimeSources.Length == 0) return new(null, source, [new("WF4002", "JVM runtime sources are missing from the compiler installation.", source.Location(1))]);
        ProcessResult result;
        try
        {
            result = await ToolProcess.RunAsync("javac", new[] { "-J-Duser.language=en", "-J-Duser.country=US", "--release", "21", "-encoding", "UTF-8", "-g", "-XDrawDiagnostics", "-d", classes, sourcePath }.Concat(runtimeSources), cancellation: cancellation);
        }
        catch (System.ComponentModel.Win32Exception error) { return new(null, source, [new("WF4202", $"Cannot start javac: {error.Message}", source.Location(1))]); }
        if (result.ExitCode != 0) return new(null, source, TranslateDiagnostics(source, result.StandardError));
        var runtimeArtifact = Path.Combine(outputDirectory, "weft-runtime.jar");
        var artifact = Path.Combine(outputDirectory, name + ".jar");
        foreach (var args in new[]
        {
            new[] { "--create", "--file", runtimeArtifact, "-C", classes, "weft" },
            new[] { "--create", "--file", artifact, "--main-class", "WeftProgram", "-C", classes, "." }
        })
        {
            try { result = await ToolProcess.RunAsync("jar", args, cancellation: cancellation); }
            catch (System.ComponentModel.Win32Exception error) { return new(null, source, [new("WF4202", $"Cannot start jar: {error.Message}", source.Location(1))]); }
            if (result.ExitCode != 0) return new(null, source, [new("WF4201", "jar: " + result.StandardError.Trim(), source.Location(1))]);
        }
        return new(artifact, source, []);
    }

    public static ImmutableArray<Diagnostic> TranslateDiagnostics(GeneratedSource source, string output)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        foreach (var line in output.Split('\n'))
        {
            var match = JavacDiagnostic().Match(line);
            if (match.Success) diagnostics.Add(new("WF4201", "javac: " + match.Groups[2].Value, source.Location(int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture))));
        }
        if (diagnostics.Count == 0) diagnostics.Add(new("WF4201", "javac: " + output.Trim(), source.Location(1)));
        return diagnostics.ToImmutable();
    }
    [GeneratedRegex(@"^.*?\.java:(\d+):\d+: (.+)$", RegexOptions.CultureInvariant)]
    private static partial Regex JavacDiagnostic();
}
